version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    networks:
      - trxapp

  myapp:
    build: .
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    restart: on-failure
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
      TEST_POSTGRES_HOST: postgres
      TEST_POSTGRES_PORT: 5432
      TEST_POSTGRES_USER: myuser
      TEST_POSTGRES_PASSWORD: mypassword
      TEST_POSTGRES_DB: mydb
    networks:
      - trxapp

networks:
  trxapp:
    driver: bridge